config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  

  resources :articles
  resources :projects
  resources :contacts, only:[:new, :create]

  root "welcome#index"

end

app/models/article.rb
class Article < ActiveRecord::Base
 extend FriendlyId

 before_validation { image.clear if @delete_image }
   has_attached_file :image,
     :styles => {  :large => "600x600>",:medium => "300x300>", :thumb => "150x150#"  },
     :storage => :dropbox,
     :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
     :dropbox_options => {
       :path => proc { |style| "#{style}/#{id}_#{image.original_filename}"},
       :unique_filename => true
     }
   #validates :image, :attachment_presence => true
   # Validate content type
   validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
   # Validate filename
   validates_attachment_file_name :image, :matches => [/png\Z/, /jpe?g\Z/, /jpg\Z/]

   def delete_image
     @delete_image ||= false
   end

   def delete_image=(value)
     if value
       self.image = nil
     end
     @delete_image  = !value.to_i.zero?
   end



 friendly_id :title, use: :slugged
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true
  attribute :nickname,  :captcha  => true


	 def headers
	  	{
		  	:subject => "Contact Form",
		  	:to => "igor.p.r.vieira@gmail.com",
		  	:from => %("#{name}" <#{email}>)
		}
    end

end

app/models/project.rb
class Project < ActiveRecord::Base
 extend FriendlyId

 before_validation { image.clear if @delete_image }
   has_attached_file :image,
     :styles => {  :large => "600x600>",:medium => "300x300>", :thumb => "150x150#"  },
     :storage => :dropbox,
     :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
     :dropbox_options => {
       :path => proc { |style| "#{style}/#{id}_#{image.original_filename}"},
       :unique_filename => true
     }
   #validates :image, :attachment_presence => true
   # Validate content type
   validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
   # Validate filename
   validates_attachment_file_name :image, :matches => [/png\Z/, /jpe?g\Z/, /jpg\Z/]

   def delete_image
     @delete_image ||= false
   end

   def delete_image=(value)
     if value
       self.image = nil
     end
     @delete_image  = !value.to_i.zero?
   end



 friendly_id :title, use: :slugged
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only:[:show, :edit, :update, :destroy]


  def index
    @articles = Article.order("created_at DESC").paginate(page: params[:page], per_page: 3)
  end

  def show
   
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new article_params
    if @article.save
      redirect_to articles_path, notice: "The article has been successfully created."
    else
      render action: "new"
    end
  end

  def edit
   
  end

  def update
    if @article.update_attributes(article_params)
      redirect_to articles_path, notice: "The article has been successfully updated."
    else
      render action: "edit"
    end
  end

  def destroy   
    @article.destroy
    redirect_to articles_path
  end

private

  def article_params
    params.require(:article).permit(:title, :body,:image, :slug)
  end


  def find_article
    @article = Article.friendly.find(params[:id])
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new
		@contact = Contact.new
	end

	def create
		@contact = Contact.new(params[:contact])
		@contact.request = request
		if @contact.deliver
			flash.now[:error] = nil
		else
			flash.now[:error] = 'Cannot send message'
			render :new
 		end
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :find_project, only:[:show, :edit, :update, :destroy]

	def index
    @projects = Project.order("created_at DESC").paginate(page: params[:page], per_page: 3)
  end

  def show
   
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new project_params
    if @project.save
      redirect_to projects_path, notice: "The article has been successfully created."
    else
      render action: "new"
    end
  end

  def edit

  end

  def update
    if @project.update_attributes(article_params)
      redirect_to projects_path, notice: "The article has been successfully updated."
    else
      render action: "edit"
    end
  end

  def destroy   
    @project.destroy
    redirect_to articles_path
  end

private

  def project_params
    params.require(:project).permit(:title, :body,:image)
  end

  def find_project
    @project = Project.friendly.find(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	   def index
	   	 @projects = Project.order("created_at DESC")	   	
	   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
   
    
    var disqus_config = function () {
        this.page.url = '<%= url_for([@article, {only_path:false}])%>'; 
        this.page.identifier = '<%= @article.id %>'; 
        this.page.title = '<%= @article.title %>'; 
    };
    
    (function() {  // REQUIRED CONFIGURATION VARIABLE: EDIT THE SHORTNAME BELOW
        var d = document, s = d.createElement('script');
        
        s.src = '//tripfotografia.disqus.com/embed.js'; 
        
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <ul>
    <%= @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_for @article, html: { multipart: true } do |f| %>
  
  <div>
    <%= f.file_field :image %>
  </div>
  <div>
    <%= f.label :title %>
  </div>
  <div>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :body %>
  </div>
  <div>
    <%= f.cktext_area :body, rows: 20 %>
  </div>
  <br>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="description">
	<h3> Edit Article</h3>
	<%= render "form" %>

</div>

app/views/articles/index.html.erb
<section class="description">
	<hr class="style-eight"></hr>
</section>
<section class="blog_context">

<% @articles.each do |article| %>
  

  <%= image_tag article.image%>
  <h3><%= article.title.html_safe %></h3>
  <div><%= article.body.first(350).html_safe %></div>
    <%= link_to "Mais", article_path(article) %> |
  <%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: 'Are you sure?' } %> |
 <%= link_to "Edit Article", edit_article_path(article) %>
   
   <div><%= article.created_at.strftime("%b %d, %Y")%></div>
   <hr />
 
<% end %>

 <h1 align="center"><%= will_paginate @project %></h1>


</section>

app/views/articles/new.html.erb
<div class="description">
	<h3> New Article</h3>
	<%= render "form" %>

</div>

app/views/articles/show.html.erb
<section class="description">
	<hr class="style-eight"></hr>
</section>

<section class="blog_context">
 <h3><%= @article.title%></h3>
 <div><%= @article.body.html_safe%></div>
 <div><%= @article.created_at.strftime("%b %d, %Y")%></div>
 <%= render 'disqus' %>
</section>

app/views/contacts/create.html.erb
 <section class="description">
    <hr class="style-eight"></hr>
       <h1>Muito Obrigado! =]</h1>
</section>

app/views/contacts/new.html.erb
 <section class="description">
    <hr class="style-eight"></hr>
          <p>Olá!</p>
          <p>Deixa a gente registrar as melhores parte da sua vida.</p>
	    <div class="blog_context">
	    	  <%= form_for @contact do |f| %>
		<%= f.label :name%>
		<%= f.text_field :name, required:true%>

		<br>

		<%= f.label :email%><br>
		<%= f.email_field :email, required:true%>

		<br>

		<%= f.label :message%><br>
		<%= f.text_area :message, as: :text%><br>

		<div class="hidden">
			<%= f.label :nickname%><br>
			<%= f.text_area :nickname, hint: 'leave this field blank'%><br>
		</div>
		<%= f.submit 'Send Message', class: 'button'%><br>
	<% end %>
	    </div>
</section>

app/views/layouts/_footer.html.erb
<section class="description">
	<hr class="style-eight"></hr>
			<a href="" class="topo"><i class="fa fa-arrow-up fa-2x"></i></a>
			<footer class="site-footer">

			  <div class="wrapper">

			    <h2 class="footer-heading">TRIP Fotografia</h2>

			    <div class="footer-col-wrapper">
			      <div class="footer-col footer-col-1">
			        <ul class="contact-list">
			          <li>Telefone:</li>
			          <li><a href="tel:+62993161606">(62) 99316-1606</a></li>
			          <li><a href="tel:+62993161606">(62) 8124-0393</a></li>
			        </ul>
			      </div>

			      <div class="footer-col footer-col-2">
			        <ul class="social-media-list">

			          <li>
			            <a href="https://www.instagram.com/tripfotografia/"><i class="fa fa-instagram" aria-hidden="true"></i> Instagram</a>
			          </li>



			          <li>
			           <a href="https://www.facebook.com/profile.php?id=415695338586976&ref=ts&fref=ts"> <i class="fa fa-facebook" aria-hidden="true"></i>  Facebook</a>
			          </li>



			          <li>
			           <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i>  Twitter</a>
			          </li>
			        </ul>
			      </div>


			    </div>

			  </div>

			</footer>
		</section>
	</div>

app/views/layouts/_navbar.html.erb
<div class="container">
    <nav>
    <ul>
		<li><%= link_to 'Home', root_path%></li>
		<li><%= link_to 'Fotos', projects_path%></li>
        <li><%= link_to 'Blog', articles_path%></li>
		<li><%= link_to 'Contato', new_contact_path%></li>   
        <li><%= link_to 'Novo Post', new_article_path%></li>
        <li><%= link_to 'Novo Album', new_project_path%></li>
        
    </ul>
    
    <div class="handle">
        <button class="hamburger" type="button">
          <span class="hamburger-box">
            <span class="hamburger-inner"></span>
          </span>
        </button>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=edge"> 
  <meta name="viewport" content="width=device-width, initial-scale=1"> 
  <meta charset="utf-8">
  <title>Trip Fotografia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://use.fontawesome.com/6955255fc8.js"></script>
</head>
<body>

    <%= render 'layouts/navbar'%>

    <%= yield %>

    <%= render 'layouts/footer'%>


</body>
</html>

app/views/projects/_form.html.erb
<% if @project.errors.any? %>
  <ul>
    <%= @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_for @project, html: { multipart: true } do |f| %>
  
  <div>
    <%= f.file_field :image %>
  </div>
  <div>
    <%= f.label :title %>
  </div>
  <div>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :body %>
  </div>
  <div>
    <%= f.cktext_area :body, rows: 20 %>
  </div>
  <br>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="description">
	<h3> Edit Project</h3>
	<%= render "form" %>

</div>

app/views/projects/index.html.erb
<section class="description">
	<hr class="style-eight"></hr>
</section>
<section class="blog_context">

<% @projects.each do |project| %>
  

  <%= image_tag project.image%>
  <h2><%= project.title.html_safe %></h2>
  <div><%= project.body.first(350).html_safe %></div>
    <h3><%= link_to "Mais", project_path(project) %> </h3>|
  <%= link_to 'Delete', project_path(project), method: :delete, data: { confirm: 'Are you sure?' } %> |
  <%= link_to "Edit Article", edit_project_path(project) %>
  
  <div><%= project.created_at.strftime("%b %d, %Y")%></div>
  <hr />
 
<% end %>

 <h1 align="center"><%= will_paginate @project %></h1>
</section>

app/views/projects/new.html.erb
<div class="description">
	<h3> New Project</h3>
	<%= render "form" %>

</div>

app/views/projects/show.html.erb
<section class="description">
	<hr class="style-eight"></hr>
</section>

<section class="blog_context">
 <h3><%= @project.title%></h3>
 <div><%= @project.body.html_safe%></div>
 <div><%= @project.created_at.strftime("%b %d, %Y")%></div>
</section>

app/views/welcome/index.html.erb
	<section class="description">
	<hr class="style-eight"></hr>
	
		

	

	 	
	 	<ul class="list-image">
	 	 <% @projects.each do |project| %>
			<li class="pass-image">
					<%= image_tag project.image,class:"img-flex"%>
	 	
			</li>
			<% end %>
		</ul>
		
		
		
	
	
	
	
	</section>